### ISSUE TITLE
js-framework 新增错误捕获机制

### ISSUE THREAD

**Issue by MengWei-OPPO** [hapjs-platform/hapjs#547]
#### 一. 需求背景

​	快应用目前对于代码的错误提示非常不友好，当代码运行出现错误时，不会在控制台有任何错误提示，导致开发者定位问题异常困难。想要捕获错误，必须在 `app.ux` 里定义 `onError `钩子，通过该钩子输出错误信息，虽然能得到部分错误信息，但是想要精确快速地定位错误，还是有一些难度，而且存在必须定义钩子函数这个硬伤。

​	所以，想要在此基础上，进一步优化快应用的错误捕获机制，提升开发者的调试体验。预期实现如下效果：

+ 用户无需手动定义任何钩子函数，当代码出错时，控制台能正常输出错误；
+ 提供全新机制的错误捕获钩子，用户可以选择全局捕获，也可以选择单独捕获某个组件或页面的错误，并且基于该钩子，进行错误上报；
+ 丰富错误提示，在输出基本错误信息的情况下，额外提供错误所在组件的 `vm` 对象以及附加错误信息，帮助开发者更快定义错误所在位置。

 

#### 二. 实现方案

​	在前端框架层对用户侧输入的代码，提供最大的错误捕获支持，不涉及客户端的修改。预计新增两个生命周期钩子：

+ `app` 新增 `onErrorHandler` 生命周期钩子，用于全局错误捕获
+ 页面和组件新增 `onErrorCaptured`生命周期钩子，用于局部错误捕获

#### 三. 错误捕获场景

​	既然涉及到错误捕获，那么错误捕获场景就是绕不开的，需要框架层，尽可能的涵盖更多的捕获场景，尽可能的捕获用户侧输入的代码错误。目前的错误捕获场景如下：

+ data()
+ 组件编译
+ watcher 表达式
+ watcher 回调
+ $nextTick 回调
+ 自定义指令回调
+ 组件事件回调
+ 组件方法回调
+ 接口方法回调
+ $emit、$dispatch、$broadcast 事件回调
+ 生命周期回调（包括 app、页面、组件）
+ setTimeout、setInterval、requestAnimationFrame 回调

以上基本上覆盖了绝大部分用户侧的代码输入场景，但也有可能存在暂时遗漏的场景，所以也做了兜底逻辑，同时接入了`onError`的那一套机制，这样，即使有遗漏的场景，也能捕获到错误，只是错误信息没有这么丰富。后续如果发现遗漏的场景，补充上错误捕获即可。

##### 1. onErrorCaptured

+ **类型**：`(err: Error, vm: Component, info: string) => ?boolean`

+ **描述**：在捕获到自身以及后代组件的错误时被触发，该生命周期钩子会收到三个参数：错误对象、错误所在的组件实例以及附加的错误来源信息。可以在回调中 `return false` 以阻止错误继续向上传播。

​	ps：`vm`（组件实例对象）可能不存在，取决于捕获到错误时，是否能拿到 `vm` 对象。

+ **错误传播规则**
  - 在框架捕获到错误时，如果此时能拿到 `vm`对象， 错误将会由子组件冒泡到父组件，逐个触发页面或组件的  `onErrorCaptured`  钩子，直至全局的 `onErrorHandler` 钩子，中间可通过 `return false` 来阻止错误继续传递；如果此时拿不到`vm`对象，错误将直接发送给全局的 `onErrorHandler` 钩子；

  - 如果 `onErrorCaptured` 钩子自身抛出了一个错误，则这个新错误和原本被捕获的错误都会发送给全局的 `onErrorHandler` 钩子。

+ **使用方法**：与其他页面或组件的生命周期使用方法保持一致，直接在页面或组件的 `*.ux`中定义，或者以插件的方式进行混入。

+ **示例代码**：

```javascript
onErrorCaptured(err, vm, info) {
  console.error('onErrorCaptured: ', err, vm, info)
	// 可通过 return false 阻止错误继续传递
  // return false
}
```

##### 2. onErrorHandler

- **类型**：`(err: Error, vm: Component, info: string) => void`
- **描述**：在捕获到快应用运行错误时被触发，该生命周期钩子的参数与  `onErrorCaptured`    一致，分别是：错误对象、错误所在的组件实例以及附加的错误来源信息。当  `onErrorHandler`  未定义时，被捕获的错误将由 `console.error` 进行输出。
- **使用方法：**与其它 `app`的 生命周期使用方法保持一致，直接在 `app.ux` 中定义，需要注意的是，  `onErrorHandler`  需保证全局唯一，不支持以插件的方式进行混入。

+ **示例代码**：

```javascript
onErrorHandler (err, vm, info) {
  console.error('onErrorHandler: ', err, vm, info)
}
```

**Comment by ChelesteWang** [comment]
@MengWei-OPPO 大致哪个版本的 js-framework 可以支持开发者使用，涉及客户端调试器的版本大约是什么，有没有具体的落地时间

**Comment by MengWei-OPPO** [comment]
该功能为 1300 的提案，预计将跟随 v1300 的联盟预览版进行发布，各产商的支持时间可能会提前，时间暂不确定。
